# See: https://docs.haskellstack.org/en/stable/travis_ci/
sudo: false

language: generic

branches:
  only:
    - develop

before_install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

env:
  - PATH=$HOME/.local/bin:$PATH

cache:
  directories:
    - $HOME/.stack

install: stack build --no-terminal --install-ghc --only-dependencies

script:
  - stack build
  - stack exec boeingx rebuild

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: _site
  target-branch: master
  on:
    branch: develop
